### PR TITLE
Housekeeping. Simplify wording. Make it more spec-like.

### PR DESCRIPTION
**Pull request by ghost**
- Put the spec as the readme so that it's up front (I often see myself jumping across the 3 files).
- Removed the authoring piece. [That's now in the docs](https://ractive.js.org/api/#component-files). 
- More concise descriptions. If there's one thing I don't like about specs, it's that they're long.
- No specific mention of implementation. Keeps it neutral.
- Removed implementation-specific examples. I'll leave that to the implementations to document.
- .editorconfig

### CODE REVIEW

**Comment by fskreuz** [comment]
Thoughts anyone? @evs-chris @Rich-Harris @MartinKolarik

**Comment by Rich-Harris** [comment]
makes sense to me 👍

**Comment by evs-chris** [comment]
I like all of those points. 😄

I must admit though that I'm not a huge fan of the component spec as it currently stands. It made a ton of sense when requirejs was the main loader-y thing that _everyone_ used, but it seems a bit limiting now with bundlers making es modules widely available.

**Comment by fskreuz** [comment]
@evs-chris can this be merged. I would like to use the reworded version for reference. :D

**Comment by evs-chris** [comment]
You should now have the technology. 😄

**Comment by fskreuz** [comment]
image

**Pull request merged**
